# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=frontend-project-44
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file.
sonar.sources=src,bin

# Exclude node modules from analysis
sonar.exclusions=node_modules/**, coverage/**

# Tests and coverage
sonar.tests=__tests__
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.js, **/__tests__/**
